# Generated by Django 5.2.15 on 2026-07-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plan_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
