# Generated by Django 5.2.15 on 2026-08-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_plan_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterscript',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chapterscript',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
