# Generated by Django 5.2.15 on 2026-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_chapterscript_duration_chapterscript_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceover',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
