# Generated by Django 5.2.15 on 2026-08-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_voiceover_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterscript',
            name='script_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='script_hash_at_generation',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='voiceovers/'),
        ),
    ]
