# Generated by Django 5.2.15 on 2026-08-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_chapterscript_script_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceover',
            name='accent',
            field=models.CharField(blank=True, default='British (RP)', max_length=50),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='audio_profile',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='pace',
            field=models.CharField(blank=True, default='Natural', max_length=50),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='style',
            field=models.CharField(blank=True, default='Documentary', max_length=50),
        ),
    ]
