# Generated by Django 6.0.6 on 2026-09-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_voiceover_accent_voiceover_audio_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprompt',
            name='prompt_no',
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='aspect_ratio',
            field=models.CharField(blank=True, default='16:9', max_length=20),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='color_palette',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='image_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='lighting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='mood',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_prompts', to='projects.project'),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='prompt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='status',
            field=models.CharField(default='Ready for generation', max_length=50),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='visual_style',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectVisualSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_style', models.CharField(blank=True, default='Cinematic Documentary', max_length=100)),
                ('image_type', models.CharField(blank=True, default='Photorealistic', max_length=100)),
                ('mood', models.CharField(blank=True, default='Serious', max_length=100)),
                ('lighting', models.CharField(blank=True, default='Cinematic', max_length=100)),
                ('color_palette', models.CharField(blank=True, default='Muted', max_length=100)),
                ('aspect_ratio', models.CharField(blank=True, default='16:9', max_length=20)),
                ('images_per_minute', models.PositiveIntegerField(default=12)),
                ('custom_style', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_settings', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_number', models.PositiveIntegerField(default=1)),
                ('prompt_text', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('visual_style', models.CharField(blank=True, default='', max_length=100)),
                ('motion_description', models.TextField(blank=True, default='')),
                ('camera_movement', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Ready for generation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_prompts', to='projects.chapter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_prompts', to='projects.project')),
            ],
        ),
    ]
