# Generated by Django 6.1.1 on 2026-09-08 17:01

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_imageprompt_prompt_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation_prompt', models.TextField(blank=True, default='')),
                ('script_segment', models.TextField(blank=True, default='')),
                ('duration_seconds', models.PositiveIntegerField(default=5)),
                ('camera_movement', models.CharField(choices=[('slow_zoom_in', 'Slow Zoom In'), ('slow_zoom_out', 'Slow Zoom Out'), ('pan_left', 'Pan Left'), ('pan_right', 'Pan Right'), ('tilt_up', 'Tilt Up'), ('tilt_down', 'Tilt Down'), ('dolly_in', 'Dolly In'), ('dolly_out', 'Dolly Out'), ('orbit', 'Orbit'), ('static_cinematic', 'Static Cinematic'), ('handheld', 'Handheld'), ('automatic', 'Automatic')], default='slow_zoom_in', max_length=50)),
                ('motion_intensity', models.CharField(choices=[('subtle', 'Subtle'), ('low', 'Low'), ('medium', 'Medium'), ('strong', 'Strong')], default='subtle', max_length=20)),
                ('animation_style', models.CharField(blank=True, default='', max_length=100)),
                ('camera_style', models.CharField(choices=[('cinematic', 'Cinematic'), ('documentary', 'Documentary'), ('dynamic', 'Dynamic'), ('static', 'Static'), ('smooth', 'Smooth'), ('dramatic', 'Dramatic')], default='cinematic', max_length=50)),
                ('motion_instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('not_generated', 'Not Generated'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='not_generated', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=projects.models.animated_video_upload_path)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animated_videos', to='projects.chapter')),
                ('generated_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animated_videos', to='projects.generatedimage')),
                ('image_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animated_videos', to='projects.imageprompt')),
            ],
            options={
                'unique_together': {('image_prompt',)},
            },
        ),
    ]
