# Generated by Django 6.1.1 on 2026-09-08 17:26

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_animatedvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='projectvisualsettings',
            name='color_palette',
        ),
        migrations.RemoveField(
            model_name='projectvisualsettings',
            name='custom_style',
        ),
        migrations.RemoveField(
            model_name='projectvisualsettings',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='projectvisualsettings',
            name='lighting',
        ),
        migrations.RemoveField(
            model_name='projectvisualsettings',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='projectvisualsettings',
            name='visual_style',
        ),
        migrations.RemoveField(
            model_name='voiceover',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='voiceover',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='voiceover',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='voiceover',
            name='script_hash_at_generation',
        ),
        migrations.RemoveField(
            model_name='voiceover',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='projectvisualsettings',
            name='video_quality',
            field=models.CharField(choices=[('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], default='1080p', max_length=20),
        ),
        migrations.CreateModel(
            name='FinalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assembling', 'Assembling'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=projects.models.final_video_upload_path)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_video', to='projects.project')),
            ],
        ),
    ]
