# Generated by Django 6.1.1 on 2026-09-08 17:28

import datetime
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_generatedimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 8, 17, 28, 56, 382220, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image_file',
            field=models.ImageField(default='', upload_to=projects.models.generated_image_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voiceover',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=projects.models.voiceover_upload_path),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 8, 17, 28, 56, 382682, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voiceover',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='script_hash_at_generation',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
