# Generated by Django 6.1.1 on 2026-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_generatedimage_created_at_generatedimage_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvisualsettings',
            name='visual_style',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
