# Generated by Django 6.1.1 on 2026-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectvisualsettings_visual_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animatedvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
