# Generated by Django 6.0.6 on 2026-06-30 14:32

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE projects_profile RENAME TO accounts_profile;',
                    reverse_sql='ALTER TABLE accounts_profile RENAME TO projects_profile;',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Profile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('display_name', models.CharField(blank=True, max_length=150)),
                        ('email', models.EmailField(blank=True, max_length=255)),
                        ('phone_number', models.CharField(blank=True, max_length=20)),
                        ('bio', models.TextField(blank=True)),
                        ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_picture_upload_path)),
                        ('full_name', models.CharField(blank=True, max_length=150)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ]
        )
    ]
